### ISSUE TITLE
Where to download those files and datas

### ISSUE THREAD

**Issue by jk456445** [human-3d/SyntheticHumanDataset#3]
Sorry for bothering, may I ask where to obtain these folders and their contents? 
I haven't seen any instructions on how to get them, so I would like to inquire about the method.
![pic](https://github.com/human-3d/SyntheticHumanDataset/assets/81965933/158bfbf0-ef72-4710-92f2-37512c3779e0)

**Comment by yunhanwang1105** [comment]
https://github.com/human-3d/Human3D/issues/5#issue-2020382356
